### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by r0nnie-b** [meraki/automation-scripts#11]
python manageadmins.py -k 12345 -o /all -c add -a test1@1.com -n test1 -p read-only
  File "manageadmins.py", line 44
    42 import sys, getopt, requests, json, time
       ^
SyntaxError: invalid syntax

python --version
Python 3.8.0

pip list
Package    Version
---------- ----------
certifi    2019.11.28
chardet    3.0.4
idna       2.8
pip        19.3.1
requests   2.22.0
setuptools 41.2.0
urllib3    1.25.7

**Comment by mpapazog** [comment]
Could you check if you have accidentally copied line numbers as well? You can find the script in its raw form here: https://raw.githubusercontent.com/meraki/automation-scripts/master/manageadmins.py

**Comment by r0nnie-b** [comment]
<insert ding ding meme here> i'm a tool.... thanks it's working fine.
