### ISSUE TITLE
addroutes.py - No ability to set Active Status

### ISSUE THREAD

**Issue by RyanVilliers** [meraki/automation-scripts#14]
Needing to be able to set my Active Status to "While Next Hop Responds to Ping" compared to "Always".

**Comment by mpapazog** [comment]
Unfortunately such a parameter is not available in the API right now, so this request cannot be implemented. Feel free to participate in the ongoing development of the Meraki APIs by joining the Developer Early Access Program: https://developer.cisco.com/meraki/meraki-developer-early-access-program/
