### ISSUE TITLE
cloneprovision has vlan bugs

### ISSUE THREAD

**Issue by cainh** [meraki/automation-scripts#15]
When creating multiple networks from a single existing network, the script does not cater correctly for multiple entries in the input.csv file.  The vlans are spread across all networks that you create.

**Comment by mpapazog** [comment]
Could you provide an example of an input file you have issues with, so I can test? Please change serial numbers into something meaningless before you send it.

**Comment by cainh** [comment]
Hi,

I have attached a debug showing the problem.  The vlans list is not unique to each instance of retVal so it just gets added to the list of vlans.  That list is populated across all instances of retVal.  See attached screenshot. CSV file renamed to TXT so that I can upload here.
[netData.txt](https://github.com/meraki/automation-scripts/files/5040677/netData.txt)
![meraki script debug](https://user-images.githubusercontent.com/16662119/89634018-08cebc00-d8e8-11ea-8666-e80689ba8032.jpg)

**Comment by mpapazog** [comment]
Thank you for reporting this bug!

I found errors in class definitions, which were causing this issue. Could you please retest using the latest version of the script and let me know if it is now behaving as it should?

**Comment by cainh** [comment]
I've had a quick look at your code and it looks like it would sort the issues out. Unfortunately I will only be able to test this weekend.  Will update you then.

**Comment by cainh** [comment]
All good now.  Thanks for the quick fix.
