### ISSUE TITLE
Need API call for % devices offline in the network

### ISSUE THREAD

**Issue by rupertwever** [meraki/automation-scripts#16]
Dashboard Organization overview has an available column that displays "% offline"
Need help finding the equivalent API calls.
Thanks

**Comment by mpapazog** [comment]
Hi,

You can achieve this with the GET /organizations/{organizationId}/devices/statuses endpoint: https://api.meraki.com/api_docs/v1#list-the-status-of-every-meraki-device-in-the-organization
If you want to resolve networkIds to network names, you will also need to call GET /organizations/{organizationId}/networks: https://api.meraki.com/api_docs/v1#list-the-networks-that-the-user-has-privileges-on-in-an-organization

The algorithm could look something like this:
Get device statuses
Get organization networks
For each device in device statuses
- If status is up, increase count_of_devices_up for the networkId it belongs to
- If status is down, increase count_of_devices_down for the networkId it belongs to
For each network in organization networks
- Calculate up/down percentages and display them
