### ISSUE TITLE
Migrate code to new API

### ISSUE THREAD

**Issue by damso** [meraki/automation-scripts#17]
Hello,

Do you have the possibility to migrate two scripts to the new APIv1?
export_mx_s2svpn.py and import_mx_s2svpn.py

I tried to do it myself. 
from:
`    fw_rules = meraki.getmxvpnfwrules(api_key, org_id)
`
to
`m = meraki.DashboardAPI(api_key=api_key, log_file_prefix=__file__[:-3])
fw_rules = m.appliance.getOrganizationApplianceVpnVpnFirewallRules(org_id)`

but I get the error:
csv_row = [rule['policy'], rule['protocol'], rule['srcCidr'], rule['srcPort'], rule['destCidr'], rule['destPort'], rule['comment'], rule['syslogEnabled']] 
**TypeError: string indices must be integers**

**Comment by fatalglitch** [comment]
Are these ever going to be updated? A lot of these no longer work because you changed the API and Libs without changing this codebase.

**Comment by mpapazog** [comment]
The creator of those scripts is no longer in Meraki, but I will take a look at them. :)

**Comment by mpapazog** [comment]
Please test the new versions of the scripts. Changes:
* The scripts now use YAML format instead of CSV
* The scripts are now compatible with the Meraki Dashboard API v1 module
* Quite a bit of logging has been removed, to reduce filesystem/stdout clutter

**Comment by mpapazog** [comment]
Closing issue as it has been inactive for over a month. If there are issues with the updated code, please reopen it.
