### ISSUE TITLE
merakidevicecounts.py - No module named requests

### ISSUE THREAD

**Issue by rowelldionicio** [meraki/automation-scripts#2]
I copied the script to my desktop. When running it there's an error on line 22:

$python merakidevicecounts.py -k xxxx -f orglist.txt
Traceback (most recent call last):
  File "merakidevicecounts.py", line 22, in <module>
    import sys, getopt, requests, json, time
ImportError: No module named requests

**Comment by billgrant** [comment]
You need to install requests.
Try:
pip3 install requests

**Comment by rowelldionicio** [comment]
That did it! Thank you!
