### ISSUE TITLE
"mxfirewallcontrol.py" does not like "tag" filter

### ISSUE THREAD

**Issue by achill-es** [meraki/automation-scripts#22]
I've created two shell scripts that call mxfirewallcontrol.py, the first one is working fine, the second one fails (because it show no hit):

```
#!/bin/bash

python mxfirewallcontrol.py -k 547***45b -o /all -f "type:network"

#eof
```
```
#!/bin/bash

python mxfirewallcontrol.py -k 547***45b -o /all -f "type:network,tag:branch"

#eof
```

You can see the code in question is almost a 1:1 copy from https://github.com/meraki/automation-scripts/blob/master/mxfirewallcontrol_manual.pdf  on page 3 right at the bottom. Still it doesn't work.

Why? What did I miss?

**Comment by achill-es** [comment]
[ruleset.txt](https://github.com/meraki/automation-scripts/files/5960074/ruleset.txt)

**Comment by TKIPisalegacycipher** [comment]
Hi @achill-es--what is the HTTP response you get when you execute? Please provide the full response including headers at your convenience.

**Comment by achill-es** [comment]
Hey TKIPisalegacycipher,

tx for feedback! I tried to get you a Wireshark capture (see attach), but regrettably it was/is encrypted -- as it should be.
So I tried to add [
![image](https://user-images.githubusercontent.com/23724915/108841002-65b96780-75d7-11eb-8f1f-36a0041670fb.png)
](url) to the code, but it didn't work out for me. Do you know how to achieve that?

But while I tried to add sslkeylog, I realized that this is only supported for Python >3.8. This brought me to the idea that my scripts above would work "better" when called with "python3" -- and voila, it worked like a charm...

So my issue is solved for the moment.

Btw: I detected something that should have been added to the guide [https://github.com/meraki/automation-scripts/blob/master/mxfirewallcontrol_manual.pdf](url) : on page 5 under "insert-file", it should be mentioned that any input file should end with a blank line -- otherwise it complains with a very short error message about wrong file content
[isoshow-tcpstream-compressed.pcapng.gz](https://github.com/meraki/automation-scripts/files/6028800/isoshow-tcpstream-compressed.pcapng.gz)

.

**Comment by mpapazog** [comment]
Thank you for the feedback and great that you go it to work.

If you have both Python 2 and Python 3 installed on your system, you might need to use "python3" and "pip3" instead of "python" and "pip". The script was originally developed in Windows, which does not come with Python 2 preinstalled.

I will go ahead and close this issue.
