### ISSUE TITLE
Rerwite of mxfirewallcontrol.py for Dashboard API v1

### ISSUE THREAD

**Issue by mpapazog** [meraki/automation-scripts#25]
I am considering rewriting mxfirewallcontrol.py as its current form is overly complicated to work with, still uses API v0 and has no support for Policy objects. I would like to hear suggestions and feedback, for example about:
* Which features of the current script you use
* What you struggle with when using it
* What features you wish it had
* If you do one-off runs with it by hand, or have another process or scheduler launch it automatically

**Comment by austin-campbell-meraki** [comment]
Thank you very much for posting this as my organization has recently started using a large amount of policy objects and it would be a massive help if this script could be updated for API v1. The script is tremendously helpful and we often use it to mass update firewall rules for our organizations with 50+ networks.  These are often one off runs by hand when needed. Thank you for your continued work in keeping this script up to date.  The provided documentation is extremely helpful and straight forward. I have had no major issues using it.

**Comment by russb3git** [comment]
I've used many aspects of this script.  I manage an organization that has a Lab Template which contains 3 networks along with a production template for 167 networks.  As lab testing completes, I'll add the new firewall rules to the production environment- backing up rules and appending to the other template.
Thanks for all the work you've done with this.  If there is an update to V1, it'll be greatly appreciated.
