### ISSUE TITLE
<Tag> all ports with <type>

### ISSUE THREAD

**Issue by Nymdfaq** [meraki/automation-scripts#26]
Hi Guys,

first of all- GREAT WORK!.

Is there a way to tag all ports in the organisation with the type parameter, with an own created tag?

Thanks a lot. Have a great day.

**Comment by mpapazog** [comment]
So are you basically looking for a script to iterate through all MS switchports in an org and adding a user defined tag to them?

**Comment by Nymdfaq** [comment]
Yeah that is exactly what I mean. :)

**Comment by mpapazog** [comment]
Here you go: https://github.com/meraki/automation-scripts/blob/master/tag_all_ports.py

Please test it and let me know if it does the trick for you. Note that this is a quick-n-dirty script coded in between meetings. It could be made to run around 100x faster by using action batches. ;)

**Comment by mpapazog** [comment]
Ah, the script I made was matching the requirements before the last edit of your response. Hold on...

**Comment by mpapazog** [comment]
Please try the script now: https://github.com/meraki/automation-scripts/blob/master/tag_all_ports.py

**Comment by Nymdfaq** [comment]
Sorry, I am out of Office, and need to test it on next Tuesday. Thank you a lot, i will let you know next week.

**Comment by Nymdfaq** [comment]
Wanted to test it yesterday, but have trouble with the move of devices. Need to contact the support all time. Are you able to add a network filter?
for example:
python tag_all_ports.py -k <api_key> [-o <org_name>] [-n <network_name>] [-f <filter>] -t <tag>

Sorry for the circumstances and thanks a lot.

**Comment by mpapazog** [comment]
Do you need exact matches of network names, or partial ones?
For example if you have a network named "London data centre", an exact match filter would require to type the whole name and would match nothing else. A partial match filter for "London" would match your DC network, as well as all other nets with "London" in their names.
Which of the two would be more useful to you?

**Comment by Nymdfaq** [comment]
An exact match of the network name would be the better filter for me. In case that i want to tag all ports of the organisation, I am able to not use the network filter, right?

**Comment by mpapazog** [comment]
Check the latest version. Added 2 new optional parameters:
**-n <network_name>**       If defined, will apply changes only to a network with a name that matches this parameter value. If omitted, all networks will be processed
**-a <add/remove>**         Action to complete. Use value "add" to add the specified tag or "remove" to remove it. If omitted "add" is assumed

**Comment by Nymdfaq** [comment]
Works great! :) Thanks :)
