### ISSUE TITLE
Rewrite scripts to use API key saved as environment variable

### ISSUE THREAD

**Issue by rasmusbirkelund** [meraki/automation-scripts#27]
Passing the API Key as clear text variable in a terminal window is, in a sense, considered insecure.
I'm proposing rewriting the scripts such that they can check for a configured Environement variable where the API key is configured. In this way, they key isn't passed in clear text, and it is unneccessary to store keys in text files (or other storage spaces.

An example code could be 
```
API_KEY = os.environ.get('MERAKI_API_KEY', None) 
if API_KEY is None:
    raise SystemExit('Please set environment variable MERAKI_API_KEY')
else:
    API_KEY = os.environ['MERAKI_API_KEY']
```

**Comment by TKIPisalegacycipher** [comment]
Hi @rasmusbirkelund would you like to submit a pull request doing so?

**Comment by mpapazog** [comment]
Any pull requests submitted to resolve this should follow these guidelines:
* Make the environment variable method optional
* Allow for the key to be passed with the method originally in the script (CLI, YAML, etc)
* Allow for the original CLI format of the script, so that command syntax strings saved by users don't suddenly stop working
* Be compatible with existing configuration files for the script

**Comment by TKIPisalegacycipher** [comment]
The simplest way IMHO would be to use [the official Meraki SDK](https://github.com/meraki/dashboard-api-python) to handle the API calls. You'd still have to use the existing CLI capabilities but all API calls could be replaced with calls from the SDK.

**Comment by mpapazog** [comment]
The scripts that still use API v0 in this repository should be updated to v1 one way or another, so this could be a good way forward for them. The change would need some careful testing though, as implementing something like this will be more or less a total rewrite.

**Comment by TKIPisalegacycipher** [comment]
Given the relative simplicity of the API logic, I suspect that [auto-reboot](https://github.com/meraki/automation-scripts/blob/master/auto_reboot.py) would be a good place to start.

**Comment by mpapazog** [comment]
Function getApiKey in script auto_reboot.py implements this suggestion.

**Comment by mpapazog** [comment]
This is being implemented in new scripts and ones being refreshed. Closing case, but please keep using this practice when submitting code to the repository.
