### ISSUE TITLE
Terraform provider

### ISSUE THREAD

**Issue by eXeDK** [meraki/automation-scripts#28]
Hi there!

Instead of all of these automation scripts, have there been any attempts at creating a Terraform provider for some of this instead?

It would be great to store our network configuration as code and use Terraform to apply it.

**Comment by TKIPisalegacycipher** [comment]
Unsure if folks have attempted but all are welcome to develop this and if they are so kind to share it back to the community. For example, folks have created [Ansible modules for Meraki](https://docs.ansible.com/ansible/latest/collections/cisco/meraki/index.html).
