### ISSUE TITLE
Trying to run script, but getting an error Fetching Organization failed

### ISSUE THREAD

**Issue by undrwatr** [meraki/automation-scripts#3]
When I am running the copyswitchcfg script, I am getting "@ ERROR: Fetching organization failed". I verified the organization is correct for my api-key and that I have access to it with curl -L -H 'X-Cisco-Meraki-API-Key: my key' -H 'Content-Type: application/json' -X GET 'https://api.meraki.com/api/v0/organizations'

It listed all 3 organizations that I have access to.

**Comment by mpapazog** [comment]
Hi,

Are you still facing this issue?

That error message means that the script cannot find an organization with the name that was specified in command line parameter "-o <org name>". Please note that the script needs an organization name and not an organization ID.

Could you copy here the exact command line syntax you use to run the script?

Regards,
Mihail

**Comment by mpapazog** [comment]
Is "423733" the name of your organization, or is it the Organization ID? If it is the ID, you will need to replace it with the name.

**Comment by undrwatr** [comment]
Sorry I was assuming it was the network id as defined by Meraki and not the
actual name of the network. After changing the org to the actual name of
the org it works as it is supposed to.

On August 24, 2018 at 9:19:55 AM, mpapazog (notifications@github.com) wrote:

Is "423733" the name of your organization, or is it the Organization ID? If
it is the ID, you will need to replace it with the name.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/meraki/automation-scripts/issues/3#issuecomment-415809215>,
or mute the thread

**Comment by Semperverus** [comment]
Hello, I am trying to use this script and getting the same issue, but I am indeed using my organization name and NOT the ID.

I am typing `python mxfirewallcontro.py -k <my_api_key_here> -o "My Organization Inc." -c create-backup` and it spits back:

`@ ERROR 46: Fetching source organization ID failed`

Is this script too old at this point? It shouldn't matter since the API hasn't changed, it's still using v0.

**Comment by undrwatr** [comment]
Make sure you have access to the organziation and that the api key is
enabled for your profile.

**Comment by Semperverus** [comment]
I figured it out. The key needs to be put in quotes as well (this was not specified in the documentation).

Documentation:
>Script usage
>To run the script, run the command “python mxfirewallcontrol.py” in the directory where the script
resides, followed by the correct command-line arguments:
`python mxfirewallcontrol.py -k <key> -o <org> [-f <filter>] [-c <command>] [-m <mode>]`
>Elements marked <value> represent values that need to be entered. Arguments in brackets [] are optional.
Here is an example of running the script:
`python mxfirewallcontrol.py -k 1234 -o “Meraki Inc” -c create-backup`
>That command would run the script with API key 1234, find an organization named Meraki Inc and create
a local backup copy of the MX Layer 3 firewall rules for all of its configuration templates. You can find more
information on the available command line arguments in the Command line arguments section of this
manual.
>Running the script with no arguments will print the help text.

**Comment by mpapazog** [comment]
@Semperverus I submitted a new version of the script. Please check if it fixes the issue of having to use quotes on your API key.
