### ISSUE TITLE
mxfirewallcontrol.py specify cellularFirewallRules

### ISSUE THREAD

**Issue by skollrc** [meraki/automation-scripts#30]
Hi, 

What is the way to add cellular firwall rules with the script?
Regarding this doc: https://developer.cisco.com/meraki/api-latest/#!update-network-appliance-firewall-cellular-firewall-rules it shoult be possible but I don't see witch option I should use.

Best regards

**Comment by mpapazog** [comment]
Cellular firewall rules are currently outside of the scope of this script. If someone wants, they can fork it and create a variant that has the option. Quite a bit of the current code should be reusable for that use case as well.
