### ISSUE TITLE
manageadmins.py traceback

### ISSUE THREAD

**Issue by systemfailx** [meraki/automation-scripts#5]
When I run the manageadmins.py script to add an admin to every organization my API key has access too it starts to run through and then throws the following traceback error: 

Traceback (most recent call last):
  File "manageadmins.py", line 412, in <module>
    main(sys.argv[1:])
  File "manageadmins.py", line 403, in main
    cmdadd(arg_apikey, matchedorgs, arg_admin, arg_name, arg_privilege)
  File "manageadmins.py", line 273, in cmdadd
    adminid   = findadminid(orgadmins, p_email)
  File "manageadmins.py", line 193, in findadminid
    if admin['email'] == p_adminemail:
KeyError: 'email'

Any idea why it would throw this?

**Comment by mpapazog** [comment]
Hi,

Could you run this modified debug version of the script and send me the output to merakixathon@gmail.com?

It looks like you have an admin account in your organization with no email defined, which does not make sense. I would like to understand why the script ends up in such a state.

The modified script can be found here: https://github.com/mpapazog/unfinished/blob/master/manageadmins_debug_2018-12-05_1.py

Regards,
Mihail

**Comment by systemfailx** [comment]
I just sent that over to you. Thanks!

**Comment by mpapazog** [comment]
Please check if this updated version fixes the issue for you: https://github.com/meraki/automation-scripts/blob/master/manageadmins.py

**Comment by systemfailx** [comment]
This took care of it. Thank you very much!

**Comment by enviex** [comment]
When i run the command i get a syntax error

**Comment by mpapazog** [comment]
@enviex Could you copy paste here the exact syntax you use to run the script? Please mask any sensitive information, like email addresses and API keys. Do you try to run it using Python 2 (the default for some operating systems) or Python 3?

**Comment by Christopher020** [comment]
i get this syntax error when i run the script in juypter and vs code

**Comment by mpapazog** [comment]
> i get this syntax error when i run the script in juypter and vs code
> 
> Cell In[3], line 1 pythonmanageadmins.py -k -o /all -c list ^ SyntaxError: invalid syntax

You seem to be missing a space between the word "python" and the name of the script. Not sure what the syntax needs to be in those tools, but if running it from the Windows command line, you run the script as:
python manageadmins.py <parameters>

I assume you removed the API key from the copied command on purpose. If not, after "-k" you need to provide your Meraki Dashboard API key.

**Comment by Christopher020** [comment]
okay i was able to spot my error from your response and currected it.
But now when i ran it again...... python manageadmins.py -k <API> -o /all -c list, it listed nothing

**Comment by mpapazog** [comment]
Troubleshooting checklist:
Do you have the latest Python 3 and Requests modules installed?
https://www.python.org/downloads/
https://pypi.org/project/requests/

Are you using the correct API key?

Are your organizations configured for API access?
https://documentation.meraki.com/General_Administration/Other_Topics/Cisco_Meraki_Dashboard_API

**Comment by Christopher020** [comment]
Yes it is configured for api access

**Comment by Christopher020** [comment]
How do i install the latest requests?

**Comment by mpapazog** [comment]
You can find instructions here: https://pypi.org/project/requests/

**Comment by Christopher020** [comment]
I have installed it, yet still not seeing any out put..... do I need to upgrade my python to python3.11.1 or continue with the current version

**Comment by Christopher020** [comment]
Simply not produce any output at all..... Would it be possible to connect privately?

**Comment by mpapazog** [comment]
For going over the basics of interacting with the Meraki Dashboard API using Python 3, it is a good idea to start with the relevant Cisco DevNet Learning Labs: https://developer.cisco.com/learning/tracks/meraki-devnet-express/

If you manage to run the examples of that learning module, you should be able to run scripts in this repository as well.

**Comment by mpapazog** [comment]
Support for scripts in this repository is best-effort and only for fixing bugs. For more general guidance on how to run Python scripts that use API calls in your lab environment, please refer to other resources, such as the Learning Labs linked above.
